using System.Linq;
using System.Numerics; // New Horizons - edit
using Content.Client.Stylesheets; // New Horizons - edit
using Content.Client.UserInterface.Controls;
using Content.Shared.Corvax.CCCVars;
using Content.Shared.Corvax.TTS;
using Content.Shared.Speech;
using Content.Shared.StatusIcon; // New Horizons - edit
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects; // New Horizons - edit
using Robust.Client.UserInterface; // New Horizons - edit
using Robust.Client.UserInterface.Controls; // New Horizons - edit
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client.VoiceMask;

[GenerateTypedNameReferences]
public sealed partial class VoiceMaskNameChangeWindow : FancyWindow
{
    // New Horizons - edit start
    [Dependency] private IEntitySystemManager _entitySystem = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    private readonly SpriteSystem _spriteSystem;
    // New Horizons - edit end

    public Action<string>? OnNameChange;
    public Action<string?>? OnVerbChange;
    public Action? OnToggle;
    public Action? OnAccentToggle;
    public Action<string>? OnVoiceChange; // Corvax-TTS
    // New Horizons - edit start
    public Action<ProtoId<JobIconPrototype>?>? OnJobIconChanged;
    // New Horizons - edit end

    private List<(string, string)> _verbs = new();
    private List<TTSVoicePrototype> _voices = new(); // Corvax-TTS

    private string? _verb;
    private ProtoId<JobIconPrototype>? _currentJobIcon; // New Horizons - edit
    public VoiceMaskNameChangeWindow()
    {
        RobustXamlLoader.Load(this);
        // New Horizons - edit start
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();

        Tabs.SetTabTitle(0, Loc.GetString("voice-mask-tab-voice"));
        Tabs.SetTabTitle(1, Loc.GetString("voice-mask-tab-job-icon"));

        ClearJobIconButton.OnPressed += _ => OnJobIconChanged?.Invoke(null);
        BuildJobIcons();
        // New Horizons - edit end

        NameSelectorSet.OnPressed += _ =>
        {
            OnNameChange?.Invoke(NameSelector.Text);
        };

        SpeechVerbSelector.OnItemSelected += args =>
        {
            OnVerbChange?.Invoke((string?) args.Button.GetItemMetadata(args.Id));
            SpeechVerbSelector.SelectId(args.Id);
        };

        ToggleButton.OnPressed += args => OnToggle?.Invoke();
        ToggleAccentButton.OnPressed += args => OnAccentToggle?.Invoke();

        // Corvax-TTS-Start
        if (IoCManager.Resolve<IConfigurationManager>().GetCVar(CCCVars.TTSEnabled))
        {
            TTSContainer.Visible = true;
            ReloadVoices(IoCManager.Resolve<IPrototypeManager>());
        }
        // Corvax-TTS-End
    }

    public void ReloadVerbs(IPrototypeManager proto)
    {
        foreach (var verb in proto.EnumeratePrototypes<SpeechVerbPrototype>())
        {
            _verbs.Add((Loc.GetString(verb.Name), verb.ID));
        }
        _verbs.Sort((a, b) => a.Item1.CompareTo(b.Item1));
    }

    public void AddVerbs()
    {
        SpeechVerbSelector.Clear();

        AddVerb(Loc.GetString("chat-speech-verb-name-none"), null);
        foreach (var (name, id) in _verbs)
        {
            AddVerb(name, id);
        }
    }

    private void AddVerb(string name, string? verb)
    {
        var id = SpeechVerbSelector.ItemCount;
        SpeechVerbSelector.AddItem(name);
        if (verb is {} metadata)
            SpeechVerbSelector.SetItemMetadata(id, metadata);

        if (verb == _verb)
            SpeechVerbSelector.SelectId(id);
    }

    // Corvax-TTS-Start
    private void ReloadVoices(IPrototypeManager proto)
    {
        VoiceSelector.OnItemSelected += args =>
        {
            VoiceSelector.SelectId(args.Id);
            if (VoiceSelector.SelectedMetadata != null)
                OnVoiceChange!((string)VoiceSelector.SelectedMetadata);
        };
        _voices = proto
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(o => o.RoundStart)
            .OrderBy(o => Loc.GetString(o.Name))
            .ToList();
        for (var i = 0; i < _voices.Count; i++)
        {
            var name = Loc.GetString(_voices[i].Name);
            VoiceSelector.AddItem(name);
            VoiceSelector.SetItemMetadata(i, _voices[i].ID);
        }
    }
    // Corvax-TTS-End

    // New Horizons - edit start
    private void BuildJobIcons()
    {
        JobGroupGrid.DisposeAllChildren();
        IconGrid.DisposeAllChildren();

        var jobGroupButtonGroup = new ButtonGroup();
        ContainerButton? firstGroupButton = null;
        IReadOnlyList<ProtoId<JobIconPrototype>>? firstGroupIcons = null;
        ContainerButton? matchingGroupButton = null;
        IReadOnlyList<ProtoId<JobIconPrototype>>? matchingGroupIcons = null;

        var groups = _prototypeManager.EnumeratePrototypes<JobIconGroupPrototype>().ToList();

        foreach (var groupProto in groups)
        {
            if (groupProto.ID == "AdminIconGroup")
                continue;

            var groupButton = CreateGroupButton(groupProto, jobGroupButtonGroup);
            groupButton.OnPressed += _ => SetJobIcons(groupProto.Icons);

            JobGroupGrid.AddChild(groupButton);

            firstGroupButton ??= groupButton;
            firstGroupIcons ??= groupProto.Icons;

            if (_currentJobIcon != null && matchingGroupButton == null && groupProto.Icons.Contains(_currentJobIcon.Value))
            {
                matchingGroupButton = groupButton;
                matchingGroupIcons = groupProto.Icons;
            }
        }

        var selectedButton = matchingGroupButton ?? firstGroupButton;
        var selectedIcons = matchingGroupIcons ?? firstGroupIcons;

        if (selectedButton != null && selectedIcons != null)
        {
            selectedButton.Pressed = true;
            SetJobIcons(selectedIcons);
        }
    }

    private void SetJobIcons(IReadOnlyList<ProtoId<JobIconPrototype>> jobIcons)
    {
        IconGrid.DisposeAllChildren();

        foreach (var icon in jobIcons)
        {
            if (!_prototypeManager.TryIndex(icon, out var iconProto))
                continue;

            var texture = _spriteSystem.Frame0(iconProto.Icon);

            var jobIconButton = new TextureButton
            {
                Access = AccessLevel.Public,
                ToolTip = Loc.GetString(iconProto.JobName),
                TextureNormal = texture,
                SetSize = new Vector2(32, 32),
            };

            jobIconButton.OnPressed += _ => OnJobIconChanged?.Invoke(iconProto.ID);

            IconGrid.AddChild(jobIconButton);
        }
    }

    private ContainerButton CreateGroupButton(JobIconGroupPrototype groupProto, ButtonGroup buttonGroup)
    {
        var button = new ContainerButton
        {
            Access = AccessLevel.Public,
            Group = buttonGroup,
            ToggleMode = true,
            StyleClasses = { StyleClass.ButtonOpenBoth },
            Margin = new Thickness(4, 2)
        };

        button.AddChild(new BoxContainer
        {
            SeparationOverride = 6,
            Children =
            {
                new TextureRect
                {
                    Texture = _spriteSystem.Frame0(groupProto.Sprite),
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    SetSize = new Vector2(24, 24),
                    VerticalAlignment = VAlignment.Center,
                },
                new Label
                {
                    Text = Loc.GetString(groupProto.GroupName),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center,
                },
            },
        });

        return button;
    }
    // New Horizons - edit end

    public void UpdateState(string name, string? verb, bool active, bool accentHide, LocId titleText, string voice, ProtoId<JobIconPrototype>? jobIcon = null) // Corvax-TTS // New Horizons - edit
    {
        NameSelector.Text = name;
        _verb = verb;
        ToggleButton.Pressed = active;
        ToggleAccentButton.Pressed = accentHide;
        Title = Loc.GetString(titleText);
        for (int id = 0; id < SpeechVerbSelector.ItemCount; id++)
        {
            if (string.Equals(verb, SpeechVerbSelector.GetItemMetadata(id)))
            {
                SpeechVerbSelector.SelectId(id);
                break;
            }
        }

        // Corvax-TTS-Start
        var voiceIdx = _voices.FindIndex(v => v.ID == voice);
        if (voiceIdx != -1)
            VoiceSelector.Select(voiceIdx);
        // Corvax-TTS-End

        // New Horizons - edit start
        _currentJobIcon = jobIcon;
        if (jobIcon != null && _prototypeManager.TryIndex(jobIcon.Value, out var jobIconProto))
        {
            CurrentJobIcon.Texture = _spriteSystem.Frame0(jobIconProto.Icon);
            CurrentJobIconLabel.Text = Loc.GetString(jobIconProto.JobName);
            CurrentJobIcon.Visible = true;
        }
        else
        {
            CurrentJobIcon.Texture = null;
            CurrentJobIconLabel.Text = Loc.GetString("chat-speech-verb-name-none");
            CurrentJobIcon.Visible = false;
        }
        // New Horizons - edit end
    }
}
