"Изм: Спрайты":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Изм: Карты":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'
    - 'Resources/Prototypes/*/Maps/**/*.yml'

"Изм: UI":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"Изм: Шейдеры":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"Изм: Аудио":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

"Изм: Локализация":
- changed-files:
  - any-glob-to-any-file: '**/*.ftl'

"Изм: Нет C#":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files: "!**/*.cs"

# NH-Add-Start
"Изм: Прототипы": 
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Prototypes/**/*.yml'
    - 'Resources/Prototypes/*.yml'

"Изм: Гайдбук":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/ServerInfo/**/*.xml'
    - 'Resources/Prototypes/Guidebook/**/*.yml'
    - 'Resources/Prototypes/*/Guidebook/**/*.xml'
# NH-Add-End
